//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compiler.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StateMachines {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StateMachines() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compiler.Resources.StateMachines", typeof(StateMachines).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        /// , 1
        /// : 2
        /// ( 3
        /// ) 4
        /// @&lt; 5
        /// @&gt; 6
        /// # 7
        ///1 ! 1
        ///2 ! 2
        ///3 ! 3
        ///4 ! 4
        ///5 ! 5
        ///6 ! 6
        ///7 ! 7.
        /// </summary>
        internal static string Delmers {
            get {
                return ResourceManager.GetString("Delmers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        /// &amp; 1
        /// * 3
        /// / 4
        /// ; 5
        /// ( 7
        /// ) 8
        /// = 9
        /// + 10
        /// - 11
        /// @ 12
        /// # 13
        /// | 14
        /// ? 15
        /// &lt; 16
        /// &gt; 17
        ///1 ! 1
        ///2 ! 2
        ///3 ! 3
        /// = 18
        ///4 ! 4
        /// = 19
        ///5 ! 5
        ///6 ! 6
        ///7 ! 7
        ///8 ! 8
        ///9 ! 11
        ///10 ! 20
        /// = 20
        ///11 ! 21
        /// = 21
        ///12 ! 22
        /// &lt; 22
        /// &gt; 23
        ///13 ! 23
        ///14 ! 24
        ///15 ! 25
        ///16 ! 9
        /// = 24
        ///17 ! 10
        /// = 25
        ///18 ! 14
        ///19 ! 15
        ///20 ! 16
        ///21 ! 17
        ///22 ! 18
        ///23 ! 19
        ///24 ! 12
        ///25 ! 13.
        /// </summary>
        internal static string OperationSigns {
            get {
                return ResourceManager.GetString("OperationSigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        /// y 1
        /// n 2
        /// a 3
        /// e 4
        /// l 5
        /// s 6
        /// o 7
        /// b 8
        /// t 9
        /// v 62
        /// c 67
        ///1
        /// e 10
        ///2
        /// o 11
        /// u 12
        ///3
        /// s 13
        ///4
        /// q 14
        ///5
        /// o 15
        ///6
        /// y 16
        /// e 17
        ///7
        /// n 18
        /// f 19
        ///8
        /// l 20
        ///9
        /// e 21
        ///10
        /// s 22
        ///11 ! 2
        ///12
        /// m 23
        ///13 ! 3
        ///14
        /// u 24
        ///15
        /// o 25
        /// g 26
        ///16
        /// m 27
        ///17
        /// n 28
        ///18 ! 11
        ///19
        /// f 29
        ///20
        /// o 30
        ///21
        /// x 31
        ///22 ! 1
        ///23
        /// b 32
        ///24
        /// a 33
        ///25
        /// p 34
        ///26
        /// i 35
        ///27
        /// b 36
        ///28
        /// t 37
        ///29 ! 12
        ///30
        /// c 38
        ///31
        /// t 39
        ///32
        /// e 40
        ///33
        /// l 41
        ///34 ! 5
        ///35
        /// c 42
        ///36
        /// o 43
        ///37
        /// e 44
        ///38
        /// k 45
        ///39 ! 17
        ///40
        /// r 46
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReservedWords {
            get {
                return ResourceManager.GetString("ReservedWords", resourceCulture);
            }
        }
    }
}
